[package]
name = "globalize"
version = "1.0.1"
edition = "2024"

readme = "./README.md"
license = "MPL-2.0"
description = "Safe global mutables via injection into `main`"
repository = "https://github.com/Lucretiel/globalize"

[dependencies]
quote = { version = "1.0", default-features = false }
syn = { version = "3.0", default-features = false, features = [
    "full",
    "parsing",
    "printing",
    "proc-macro",
] }

[lib]
proc-macro = true
